### ISSUE TITLE
install link

### ISSUE THREAD

**Issue by a-rutnam** [freesewing/data#4]
"Full install instructions are available at freesewing.org/docs/data/install but here's the gist of it"

this link works: https://docs.freesewing.org/install

**Comment by joostdecock** [comment]
This points to where the install instructions **will be** on the new site. Basically, the entire README file is written for a time when the site is published. 

Freesewing is in early access, and the public site (freesewing.org) does not have this info until I'll properly release it.

I'm not going to change this because it just means more work later to update it again after release.

Thanks for reporting though!
